### ISSUE TITLE
spring-ui ve spring-static Uygulamaları için Dockerfile'lar

### ISSUE THREAD

**Issue by erolg** [oguzhalit/spring-docker-compose#1]
Selam Oğuz,

Bu güzel proje ve açık kaynak ekosistemine katkın için teşekkürler! Docker ve Spring-boot ile proje geliştirmek isteyen kişilere güzel bir hızlı başlangıç klavuzu olmuş.

Dockerhub'ta yayınladığın spring-ui ve spring-static imajlarına ait Dockerfile'ları da bu projeye eklemeyi düşünür müsün? 

Projeyi kullanmak isteyenlerin bu imajlarda değişiklik yapmaları gerekebilir ve tüm projeyi `docker-compose build` komutu ile ayağa kaldırmak isteyebilirler.

**Comment by oguzhalit** [comment]
Docker-File'ları direk proje ile ekledim.Biraz araştırdıkdan sonra zuul ile api gateway olayını çözebilcegimi düşünüyorum.

https://www.tutorialspoint.com/spring_boot/spring_boot_zuul_proxy_server_and_routing.htm

https://stackoverflow.com/questions/49360467/spring-cloud-default-redirecting-from-gateway-to-ui?noredirect=1&lq=1

Yukardaki kaynakları biraz daha irdelersem olucak gibi kendi spring dosyalarına ekledigimde derleme hataları alıyorum ama çözmek üzereyim.

Tam olarak bütün sıkıntıları halletdigimde anlaşılabilir ve detaylı bir şekilde mediumda yaptıklarımı adım adım anlatmayı düşünüyorum.Teşşekürler.Araştırırken çok şey ögrendim.

**Comment by oguzhalit** [comment]
Son düzenlemeler ile birlikte yeni bir repoda yayınladım.
https://github.com/oguzhalit/Spring-Docker-Haproxy

**Comment by erolg** [comment]
Ellerine sağlık.
